### ISSUE TITLE
random damage

### ISSUE THREAD

**Issue by prietzem** [prietzem/spacerex#44] opened 2023-04-30 04:42 UTC
for some reason the player can get hit randomly, idk where the issue is, but i experienced it while playing

**Comment by GuncraftaM1P** [comment] 2023-05-13 22:47
i guess it's fixed now? i rewrote rock a couple of times and i guess now that issue should be resolved. comment and reopen issue any time if needed!

**Comment by GuncraftaM1P** [comment] 2023-05-15 11:59
I managed to recreate and even film 5 instances of ghost damage, im pretty sure i know what the issue is and it could be an easy fix. looking at the code now.
Data i got from the 5 examples i caught: 
- The damage occurs always on the right side of the player
- shots don't have anything todo with the issue
- the player is on the same height (y-coordinate) of the rock
- the size of the rock doesn't matter
- player is often moving horizontally

My conclusion for a possible solution:
on the collision detection it is tested if u cross a multiple of 2 lines until the edge of the screen (a bit further actually in case there are objects right on the edge). if yes, a closed object is between u and the edge of the screen. if it is uneven, there is an open object between u and the edge, meaning that u r inside of one. if u however match ur y-coordinate with one of the corners of a rock, (and now my suspicion:) the vertex itself is only tested for one of the edges adjacent to the vertex, therefore making every corner/ vertex a possible ghost damage point. because coordinates are measured in floats however, it is extremely unlikely to hit one of the 12 vertices on a rock. the issue (in my suspicion) is a < or <= issue.

**Comment by GuncraftaM1P** [comment] 2023-05-15 12:04
if ((xIntersect >= min(p1.x, p2.x) && xIntersect <= max(p1.x, p2.x))
    && (xIntersect >= min(p3.x, p4.x) && xIntersect <= max(p3.x, p4.x))) {
    return true;
  }

i don't know what the issue is then

**Comment by GuncraftaM1P** [comment] 2023-05-15 22:14
fixed again with just setting a before requirement of the player basically being inside of the rock (not accounting the spikes that miss from the inside ti the outside of the rock) to test if it's actually inside

**Closed** 2023-05-18 22:19 UTC
Labels: bug, weird, question, wontfix
